config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#home'

  resources :bookings, only: [:index, :show] do
    resources :reviews, only: [:new, :create]
    resources :checkings, only: [:new, :create]
    patch 'cancel'
  end

  resources :vans do
    resources :bookings, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :messages, only: [:create]
  get 'dashboard', to: 'pages#dashboard'
  get 'bookings/:id/messages/new', to: 'messages#new', as: :new_message
  get 'bookings/:id/messages', to: 'messages#show', as: :show_messages

  # Route pour les vans, bookings et reservations du current_user
  get 'my_vans', to: 'vans#my_vans', as: :my_vans
  delete 'my_vans/:id', to: 'vans#destroy', as: :delete_my_van
  get 'my_bookings', to: 'bookings#my_bookings', as: :my_bookings
  get 'my_van_reservations', to: 'vans#reservations', as: :my_van_reservations

  # Routes pour accepter et refuser les réservations
  patch 'my_van_reservations/:booking_id/accept', to: 'vans#accept', as: :accept_my_van_reservation
  patch 'my_van_reservations/:booking_id/reject', to: 'vans#reject', as: :reject_my_van_reservation
end

app/models/van.rb
class Van < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :messages
  has_one_attached :photos

  geocoded_by :location  # Indique que la géolocalisation doit se faire par rapport à l'attribut `location`

  after_validation :geocode  # Déclenche la géolocalisation après la validation du modèle

  validates :title, presence: true
  validates :description, presence: true, length: { minimum: 100, message: "doit comporter au moins 100 caractères" }
  validates :price_per_day, presence: true, numericality: { greater_than: 0, message: "doit être un nombre positif" }
  validates :status, presence: true, inclusion: { in: %w(disponible réservé), message: "doit être disponible ou indisponible" }
  validates :location, presence: true
end

app/controllers/vans_controller.rb
class VansController < ApplicationController
  before_action :set_van, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @vans = Van.all
    if params[:query].present?
      @vans = @vans.where("location ILIKE ?", "%#{params[:query]}%")
    end
    if params[:dates].present?
      dates = params[:dates].split(" ")
      start_date_calendar = dates[0].to_date
      end_date_calendar = dates.last.to_date

      overlapping_bookings = Booking.where("start_date <= ? AND end_date >= ?", end_date_calendar, start_date_calendar)
      booked_van_ids = overlapping_bookings.pluck(:van_id)
      @vans = @vans.where.not(id: booked_van_ids)
    end
    @markers = @vans.geocoded.map do |van|
      {
        lat: van.latitude,
        lng: van.longitude
      }
    end
  end

  def show
    # @van est défini par set_van
  end

  def new
    @van = Van.new
  end

  def create
    @van = Van.new(van_params)
    @van.user = current_user
    @van.status = "disponible"
    if @van.save
      redirect_to @van, notice: 'Votre van est pret a vivre de belles aventures!'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @van.user = current_user
    @van.status = "disponible"
    if @van.update(van_params)
      redirect_to @van, notice: 'Votre van est beaux comme un camion'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @van.destroy
    redirect_to my_vans_path, notice: 'Votre van est de retour au garage'
  end

  def my_vans
    @vans = current_user.vans
  end

  def reservations
    @reservations = van_reservations
  end

  def van_reservations
    Booking.joins(:van).where(vans: { user_id: current_user.id }).distinct
  end

  def accept
    @booking = Booking.find(params[:booking_id])
    @booking.status = "accepté"
    raise
    @booking.save!
    redirect_to my_van_reservations_path, notice: 'Réservation acceptée.'
  end

  def reject
    @booking = Booking.find(params[:booking_id])
    @booking.status = "refusé"
    @booking.save!
    redirect_to my_van_reservations_path, notice: 'Réservation refusée.'
  end

  private

  def set_van
    @van = Van.find(params[:id])
  end

  def van_params
    params.require(:van).permit(:title, :description, :price_per_day, :location, :photos)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end
 end

app/views/vans/_form.html.erb
<%= simple_form_for(@van) do |f| %>
    <%= f.input :title, :label => 'Nom de ton van'%>
    <%= f.input :description %>
    <%= f.input :price_per_day, :label => 'Prix par jours (en €)' %>
    <%= f.input :location, :label => 'Où te situes-tu ?' %>
    <%= f.input :photos, as: :file%>
    <%= f.submit 'Valider', class: "btn btn-primary" %>
  <% end %>

app/views/vans/_reservations.html.erb
<div class="card m-3 bg-white" id="reservation_<%= reservation.id %>">
  <div class="card-body">
    <p><strong>Du <%= reservation.start_date %> au <%= reservation.end_date %></strong></p>
    <strong><%= reservation.van.title %> </strong><%= link_to "(Détail de mon van)", van_path(reservation.van) %> <br>
    <strong>Client :</strong> <%= reservation.user.name %><br>
    <strong>Status :</strong> <%= reservation.status.capitalize %><br>
    <strong>Prix :</strong> <%= number_to_currency(reservation.price, unit: '€') %>
    <div class="d-flex">
      <% if reservation.status == "attente" %>
        <%= link_to "Accepter", accept_my_van_reservation_path(reservation), data: { turbo_method: :patch, turbo_confirm: "Êtes-vous sûr de vouloir accepter cette réservation ?" }, class: "btn btn-primary" %> <br>
        <%= link_to "Refuser", reject_my_van_reservation_path(reservation), data: { turbo_method: :patch, turbo_confirm: "Êtes-vous sûr de vouloir refuser cette réservation ?" }, class: "btn btn-danger" %>
      <% end %>
    </div>
  </div>
</div>

app/views/vans/_small_van_card.html.erb
<div class="small-van-card">
  <%= image_tag 'roadpass-zRetWvOnbf0-unsplash.jpg', height: 200, width: 300, alt: 'Van Photo' %>

  <div class="van-details">
    <h3><%= van.title %></h3>
    <p><%= van.description %></p>
    <p class="price"><%= number_to_currency(van.price_per_day, unit: '€', precision: 0) %>/jour</p>
  </div>

  <%= link_to "En savoir plus", van_path(van), class: "btn btn-primary" %>
  </div>
</div>

app/views/vans/edit.html.erb
<div class="container mt-3">
  <div class="d-flex align-items-center">
    <%= link_to vans_path(@van) do %>
      <i class="fa-solid fa-arrow-left text-dark"></i>
    <% end %>
    <%= link_to 'Retour à la liste des Vans', vans_path, class: "ms-2 text-dark fw-bold link-underline-light" %>
  </div>
  <h1 class="text-center">Éditer le Van</h1>
  <%= render "form", class:"m-3"%>
</div>

app/views/vans/index.html.erb
<div class="vans-title">
  <h1>Tous les vans</h1>
</div>
<div class="row justify-content-center">
  <div class="col-sm-8 my-3">
    <%= form_with url: vans_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
           params[:query],
           class: "form-control",
           placeholder: "Lieu de ton van"
      %>
      <%= text_field_tag :dates,
      params[:dates],
        class: "form-control",
        placeholder: "Dates de location",
        data: { controller: "range-picker"  }%>
    <%= submit_tag "Rechercher", name: "", class: "btn-search" %>
  <% end %>
  </div>
</div>
<% if @vans.empty? %>
  <div class="vans-title">
    <h1>Aucun van ne correspond à ta recherche</h1>
  </div>
<% else %>
  <div class="all d-flex">
    <div class="vans-list">
      <% @vans.each do |van| %>
        <div class="small-van-card">
          <% if van.photos.attached? %>
            <%= cl_image_tag van.photos.key, class: "img-fluid"%>
          <% else %>
            <%= image_tag 'roadpass-zRetWvOnbf0-unsplash.jpg', class: "img-fluid" %>
            <% end %>
          <div class="van-details">
            <h3><%= van.title %></h3>
            <p><%= van.description %></p>
            <p class="price"><%= number_to_currency(van.price_per_day, unit: '€', precision: 0) %>/jour</p>
            <p>Ce van est proposé par : <%= van.user.name %></p>
            <%= link_to "En savoir plus", van_path(van), class: "btn btn-primary" %>
        </div>
        </div>
      <% end %>
    </div>
    <div class="map-container mt-4 custom-map-container">
      <div style="width: 100%; height: 100vh;"
       data-controller="map"
       data-map-markers-value="<%= @markers.to_json %>"
       data-map-apikey-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/vans/my_vans.html.erb
<div class="container">
  <div class="vans-title">
    <h1>Tous mes vans</h1>
  </div>

  <% if @vans.any? %>
    <div class="vans-list">
      <% @vans.each do |van| %>
        <div class="small-van-card">
          <% if van.photos.attached? %>
            <%= cl_image_tag van.photos.key, class: "img-fluid"%>
          <% else %>
            <%= image_tag 'roadpass-zRetWvOnbf0-unsplash.jpg', class: "img-fluid" %>
          <% end %>
          <div class="van-details">
            <h3><%= van.title %> - <%= van.status.capitalize %></h3>
            <div class="van-actions">
              <%= link_to 'Éditer', edit_van_path(van), class: 'btn-edit' %>
              <%= link_to 'Supprimer', delete_my_van_path(van), method: :delete, data: { turbo_confirm: 'Êtes-vous sûr?', turbo_method: :delete }, class: 'btn-delete' %>
            </div>
            <p><%= van.description %></p>
            <p class="price"><%= number_to_currency(van.price_per_day, unit: '€', precision: 0) %>/jour</p>
            <p>Ce van est proposé par : <%= van.user.name %></p>
            <%= link_to "Voir mon van", van_path(van), class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <h4 class="text-center">Vous n'avez pas encore ajouté de van...</h3>
    <h4 class="text-center">Tenté pour mettre en location ton van ?</h3>
    <%= link_to "Ajouter mon van", new_van_path, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/vans/new.html.erb
<div class="container mt-3">
  <div class="d-flex align-items-center">
    <%= link_to vans_path(@van) do %>
      <i class="fa-solid fa-arrow-left text-dark"></i>
    <% end %>
    <%= link_to 'Retour à la liste des Vans', vans_path, class: "ms-2 text-dark fw-bold link-underline-light" %>
  </div>
  <h1 class="text-center">Ajouter un Nouveau Van</h1>
  <%= render "form", class:"m-3" %>
</div>

app/views/vans/reservations.html.erb
<div class="container m-3">
  <h1 class = "text-center">Réservations de mes Vans</h1>

  <% if @reservations.any? %>
    <div class="d-flex">
      <% @reservations.each do |reservation| %>
      <div class="card m-3 bg-white">
        <div class="card-body">
          <p><strong>Du <%= reservation.start_date %> au <%= reservation.end_date %></strong></p>
          <strong><%= reservation.van.title %> </strong><%= link_to "(Détail de mon van)", van_path(reservation.van) %> <br>
          <strong>Client :</strong> <%= reservation.user.name %><br>
          <strong>Status :</strong> <%= reservation.status.capitalize %><br>
          <strong>Prix :</strong> <%= number_to_currency(reservation.price, unit: '€') %>
          <div class="d-flex">
            <% if reservation.status == "attente" %>
              <%= link_to "Accepter", accept_my_van_reservation_path(reservation), data: {turbo_method: :patch }, class: "btn btn-primary" %> <br>
              <%= link_to "Refuser", reject_my_van_reservation_path(reservation), data: {turbo_method: :patch }, class: "btn btn-danger" %>
            <% end %>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  <% else %>
    <p>Vous n'avez pas encore de réservations pour vos vans.</p>
  <% end %>
</div>

app/views/vans/show.html.erb
<div class="page-container">
  <div class="van-back">
    <%= link_to vans_path, class: 'back-link' do %>
      <span class="back-arrow">&larr;</span> Retour à la liste des Vans
    <% end %>
  </div>
  <div class="van-container">
    <div class="van-header">
      <div class="van-image">
        <% if @van.photos.attached? %>
          <%= cl_image_tag @van.photos.key, class: "img-fluid"%>
        <% else %>
          <%= image_tag 'roadpass-zRetWvOnbf0-unsplash.jpg', class: "img-fluid" %>
        <% end %>
      </div>
      <div class="van-title">
        <h1 class="van-title-font"><%= @van.title %></h1>
      </div>
    </div>
    <% if user_signed_in? && @van.user == current_user %>
      <div class="van-actions d-flex justify-content-end">
        <%= link_to 'Éditer', edit_van_path(@van), class: 'btn-edit' %>
        <%= button_to 'Supprimer', delete_my_van_path(@van), method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Êtes-vous sûr?' }, class: 'btn-delete' %>
      </div>
    <% end %>
    <div class="van-description">
      <p><%= @van.description %></p>
    </div>
    <div class="van-price">
      <p>€<%= @van.price_per_day %> /jour</p>
    </div>
    <% if user_signed_in? && @van.user == current_user %>
      <div class="van-user">
        <p>Ce van est proposé par : <%= @van.user.name %></p>
      </div>
    <% else %>
      <div class="van-reserve">
        <%= link_to 'Réserver ce Van', new_van_booking_path(@van), class: 'btn-reserve' %>
      </div>
      <div class="van-user">
        <p><em>Ce van est proposé par : <%= @van.user.name %></em></p>
      </div>
    <% end %>
    <div class="van-reviews">
      <h2>Avis</h2>
      <% if @van.reviews.any?  %>
        <% @van.reviews.each do |review| %>
          <div class="review">
            <div class="review-stars">
              <% (1..5).each do |i| %>
                <span class="star <%= 'filled' if review.rating >= i %>">★</span>
              <% end %>
            </div>
            <p><%= review.comment %></p>
          </div>
        <% end %>
      <% else %>
        <p><em>Aucun avis pour le moment</em></p>
      <% end %>
    </div>
  </div>
</div>