config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#home'

  resources :bookings, only: [:index, :show] do
    resources :reviews, only: [:new, :create]
    resources :checkings, only: [:new, :create]
    patch 'cancel'
  end

  resources :vans do
    resources :bookings, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :messages, only: [:create]
  get 'dashboard', to: 'pages#dashboard'
  get 'bookings/:id/messages/new', to: 'messages#new', as: :new_message
  get 'bookings/:id/messages', to: 'messages#show', as: :show_messages

  # Route pour les vans, bookings et reservations du current_user
  get 'my_vans', to: 'vans#my_vans', as: :my_vans
  delete 'my_vans/:id', to: 'vans#destroy', as: :delete_my_van
  get 'my_bookings', to: 'bookings#my_bookings', as: :my_bookings
  get 'my_van_reservations', to: 'vans#reservations', as: :my_van_reservations

  # Routes pour accepter et refuser les réservations
  patch 'my_van_reservations/:booking_id/accept', to: 'vans#accept', as: :accept_my_van_reservation
  patch 'my_van_reservations/:booking_id/reject', to: 'vans#reject', as: :reject_my_van_reservation
end

app/models/checking.rb
class Checking < ApplicationRecord
  STATUS = %w(attente acceptée refusée annulée)
  belongs_to :booking

  validates :comment, presence: true
  validates :check_in_date, presence: true
  validates :check_out_date, presence: true
  validates :status, inclusion: { in: STATUS }
end

app/controllers/checkings_controller.rb
class CheckingsController < ApplicationController
  before_action :set_booking, only: [:new, :create]

  def new
    @checking = @booking.checkings.new(checking_type: params[:checking_type])
  end

  def create
    @checking = @booking.checkings.new(checking_params)
    if @checking.save
      redirect_to van_path(@booking.van), notice: 'Checking was successfully created.'
    else
      render :new
    end
  end

  private

  def set_booking
    @booking = Booking.find(params[:booking_id])
  end

  def checking_params
    params.require(:checking).permit(:status, :comments, :checking_type, :booking_id, :user_id)
  end
end

app/views/checkings/new.html.erb
<h1><% if @checking.checking_type == 'pickup' %>
    Nouvel État des Lieux à la Prise
  <% else %>
    Nouvel État des Lieux au Retour
  <% end %>
</h1>
<%= form_with model: [@booking, @checking], local: true do |form| %>
  <%= form.hidden_field :checking_type %>
  <div>
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>
  <div>
    <%= form.label :comments %>
    <%= form.text_area :comments %>
  </div>
  <div>
    <%= form.submit 'Soumettre' %>
  </div>
<% end %>
<%= link_to 'Retour', van_path(@booking.van) %>

app/views/checkings/show.html.erb
<h1><%= @van.name %></h1>
<p><%= @van.description %></p>
<p>Prix: <%= @van.price %> EUR/jour</p>
<%= link_to 'Réserver ce Van', new_van_booking_path(@van) %>
<%= link_to 'Éditer ce Van', edit_van_path(@van) %>
<%= link_to 'Retour à la liste des Vans', vans_path %>

<h2>État des Lieux</h2>
<%= link_to 'État des lieux à la prise', new_booking_checking_path(@booking, checking_type: 'pickup') %>
<%= link_to 'État des lieux au retour', new_booking_checking_path(@booking, checking_type: 'return') %>