config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#home'

  resources :bookings, only: [:index, :show] do
    resources :reviews, only: [:new, :create]
    resources :checkings, only: [:new, :create]
    patch 'cancel'
  end

  resources :vans do
    resources :bookings, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :messages, only: [:create]
  get 'dashboard', to: 'pages#dashboard'
  get 'bookings/:id/messages/new', to: 'messages#new', as: :new_message
  get 'bookings/:id/messages', to: 'messages#show', as: :show_messages

  # Route pour les vans, bookings et reservations du current_user
  get 'my_vans', to: 'vans#my_vans', as: :my_vans
  delete 'my_vans/:id', to: 'vans#destroy', as: :delete_my_van
  get 'my_bookings', to: 'bookings#my_bookings', as: :my_bookings
  get 'my_van_reservations', to: 'vans#reservations', as: :my_van_reservations

  # Routes pour accepter et refuser les réservations
  patch 'my_van_reservations/:booking_id/accept', to: 'vans#accept', as: :accept_my_van_reservation
  patch 'my_van_reservations/:booking_id/reject', to: 'vans#reject', as: :reject_my_van_reservation
end

app/models/booking.rb
class Booking < ApplicationRecord
  STATUS = %w(attente acceptée terminée refusée annulée)
  belongs_to :van
  belongs_to :user
  has_one :checking, dependent: :destroy
  has_many :messages

  validates :user_id, presence: true
  validates :van_id, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  # validates :price, presence: true
  validates :status, inclusion: { in: STATUS }
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:edit, :update, :destroy]
  before_action :set_van, only: [:new, :create]
  before_action :authenticate_user!, only: [:new, :create, :show]

  def index
    @bookings = Booking.all
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.van = @van
    @booking.user = current_user
    @booking.status = "attente"
    @van.status = "réservée"
    @booking.price = @van.price_per_day * (Date.parse(@booking.end_date) - Date.parse(@booking.start_date)).to_i
    if @booking.save
      redirect_to booking_path(@booking), notice: 'Booking was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def edit
    @booking = booking_path
  end

  def update
    if @booking.update(booking_params)
      redirect_to van_bookings_path(@booking.van), notice: 'Booking was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @booking.destroy
    redirect_to van_bookings_path(@booking.van), notice: 'Booking was successfully destroyed.'
  end

  def my_bookings
    @bookings = current_user.bookings
  end

  def cancel
    @booking = Booking.find(params[:booking_id])
    @booking.update(status: "annulée")
    redirect_to van_bookings_path(@booking.van), notice: 'La réservation a été annulée.'
  end
  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def set_van
    @van = Van.find(params[:van_id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :user_id, :van_id, :price)
  end
end

app/views/bookings/edit.html.erb
<h1>Éditer la Réservation pour <%= @van.title %></h1>
<%= form_with model: [@van, @booking], local: true do |form| %>
  <div>
    <%= form.label :start_date %>
    <%= form.date_field :start_date %>
  </div>
  <div>
    <%= form.label :end_date %>
    <%= form.date_field :end_date %>
  </div>
  <div>
    <%= form.submit 'Mettre à jour' %>
  </div>
<% end %>
<%= link_to 'Retour aux Réservations', van_bookings_path(@van) %>

app/views/bookings/index.html.erb
<ul>
  <% @bookings.each do |booking| %>
    <li>
      Du <%= booking.start_date %> au <%= booking.end_date %>
<%#       <%= link_to 'Éditer', edit_van_booking_path(@van, booking) %>
      <%# <%= link_to 'Annuler', van_booking_path(@van, booking), method: :delete, data: { confirm: 'Êtes-vous sûr?' } %> %> %>
    </li>
  <% end %>
</ul>
<%= link_to 'Retour au Van', vans_path(@van) %>

app/views/bookings/my_bookings.html.erb
<div class="reservation-container">
  <div class="van-back m-3">
    <%= link_to vans_path, class: 'back-link' do %>
      <span class="back-arrow">&larr;</span> Retour à la liste des Vans
    <% end %>
  </div>

  <div class="reservation-title">
    <h1 class="custom-title">Mes réservations</h1>
  </div>

  <% if @bookings.any? %>
    <div class="reservation-list">
      <% @bookings.each do |booking| %>
        <div class="reservation-item">
          <div class="reservation-card">
            <% if booking.van.photos.attached? %>
              <%= cl_image_tag booking.van.photos.key, class: "img-fluid" %>
            <% else %>
              <%= image_tag 'roadpass-zRetWvOnbf0-unsplash.jpg', class: "img-fluid" %>
            <% end %>
            <div class="reservation-details">
              <p class="booking-date">Du <%= booking.start_date %> au <%= booking.end_date %></p>
              <h3><%= booking.van.title %> - <%= booking.status.capitalize %></h3>
              <% if booking.status == "attente" %>
                <%= link_to 'Annuler', booking_cancel_path(booking), data: { turbo_method: :patch }, class: 'btn-delete' %>
              <% end %>
              <p><%= booking.van.description %></p>
              <p class="price"><%= number_to_currency(booking.price, unit: '€', precision: 0) %>/jour</p>
              <p>Ce van est loué par : <%= booking.van.user.name %></p>
              <%= link_to "Voir ma réservation", booking_path(booking), class: "btn-view-reservation" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <h4 class="text-center">Vous n'avez pas fait de réservation...</h4>
    <h4 class="text-center">Prêt à organiser un roadtrip ?</h4>
    <%= link_to "Louer un van", new_van_path, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/bookings/new.html.erb
<!-- app/views/bookings/new.html.erb -->

<div class="container-full" data-controller="booking" data-booking-price-per-day="<%= @van.price_per_day %>">
  <div class="row justify-content-center">
    <!-- Section principale sans carte ni fond -->
    <div class="col-12 text-center booking-info">
      <h1 class="page-title">Nouvelle Réservation pour <%= @van.title %></h1>
      <div class="stars-image">
        <%= image_tag 'stars.png', class: "stars-img", alt: 'Stars Image' %>
      </div>
      <p class="lead">Nous vous accompagnons dans l'organisation de vos roadtrips, partout en France et en Europe.</p>
      <p class="lead">Prêt à faire partie d'une grande aventure ? Il ne te reste qu'à réserver ton van pour profiter pleinement !</p>
    </div>
  </div>

  <div class="row mt-4">
    <div class="col-md-8">
      <!-- Carte "Ton Van" -->
      <div class="van-card card bg-light">
        <div class="card-body">
          <% if @van.photos.attached? %>
            <%= cl_image_tag @van.photos.key, class: "card-img-top img-fluid", alt: 'Van Photo' %>
          <% else %>
            <%= image_tag 'roadpass-zRetWvOnbf0-unsplash.jpg', class: "card-img-top img-fluid", alt: 'Van Photo' %>
          <% end %>
          <div class="van-details">
            <h5 class="card-title"><%= @van.title %></h5>
            <p class="card-text"><%= @van.description %></p>
            <p class="card-text price mb-0 van-price"><%= number_to_currency(@van.price_per_day, unit: '€', precision: 0) %>/jour</p>
            <div class="van-reviews">
              <h2>Avis</h2>
              <% if @van.reviews.any? %>
                <% @van.reviews.each do |review| %>
                  <div class="review">
                    <div class="review-stars">
                      <% (1..5).each do |i| %>
                        <span class="star <%= 'filled' if review.rating >= i %>">★</span>
                      <% end %>
                    </div>
                    <p><%= review.comment %></p>
                  </div>
                <% end %>
              <% else %>
                <p><em>Aucun avis pour le moment</em></p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <!-- Carte "Informations sur la réservation" -->
      <div class="booking-info-card-new card bg-white">
        <div class="card-header">
          <h4 class="card-title">Informations</h4>
        </div>
        <div class="card-body">
          <%= simple_form_for [@van, @booking], html: { local: true }, class: "booking-form" do |f| %>
            <%= f.input :start_date, label: 'Début de ton séjour', input_html: { id: 'start_date', data: { controller: "datepicker", booking_target: "startDate" } } %>
            <%= f.input :end_date, label: 'Fin de ton séjour', input_html: { id: 'end_date', data: { controller: "datepicker", booking_target: "endDate", action: "change->booking#updateTotalPrice" } } %>
            <%= f.input :name, label: 'Nom', input_html: { value: current_user.name } %>
            <%= f.input :phone_number, label: 'Numéro de téléphone', input_html: { value: current_user.phone_number } %>
            <%= f.input :email, label: 'Email', input_html: { value: current_user.email } %>
            <%= f.input :address, label: 'Adresse', input_html: { value: current_user.address } %>

            <div id="total_price" data-booking-target="totalPrice" class="my-3">Prix Total: 0€</div>

             <div class="text-center mt-3">
              <br><%= f.submit 'Réserver', class: "btn btn-custom-reserve" %></br>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container-full">
  <div class="row justify-content-center">
    <div class="col-12 text-center booking-info-title">
      <h1 class="page-title">
        <% if @booking.status == "annulée" %>
          Réservation Annulée <i class="fa-solid fa-xmark text-danger"></i>
        <% else %>
          Réservation Validée <i class="fas fa-check text-success"></i>
        <% end %>
      </h1>
    </div>
  </div>

  <div class="row mt-4">
    <div class="col-md-8">
      <div class="card custom-booking-info-card">
        <div class="card-header">
          <h3>Reservation <%=@booking.status == "annulée"? "annulée" : "validée"%></h3>
        </div>
        <div class="card-body">
          <h5 class="custom-card-title">Vos informations</h5>
          <ul class="list-unstyled">
            <li><strong>Nom:</strong> <%= @booking.user.name %></li>
            <li><strong>Téléphone:</strong> <%= @booking.user.phone_number %></li>
            <li><strong>Email:</strong> <%= @booking.user.email %></li>
            <li><strong>Adresse:</strong> <%= @booking.user.address %></li>
            <li><strong>Prix: </strong><%= @booking.price.to_i %>€</li>
          </ul>
        </div>
        <div class="card-footer">
          <% if @booking.status == "annulée" || @booking.status == "terminée" || @booking.status == "refusée"%>
            <%= link_to 'Mes réservations', my_bookings_path(@booking) %>
          <% else %>
            <%= link_to 'Annuler la réservation', booking_cancel_path(@booking), data: { turbo_method: :patch}, class: 'btn-delete' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="row mt-4">
    <div class="col-md-8">
      <div class="van-card card bg-light">
        <div class="card-body">
          <% if @booking.van.photos.attached? %>
            <%= cl_image_tag @booking.van.photos.key, class: "img-fluid", alt: 'Van Photo' %>
          <% else %>
            <%= image_tag 'roadpass-zRetWvOnbf0-unsplash.jpg', class: "img-fluid", alt: 'Van Photo' %>
          <% end %>
          <div class="van-details">
            <h5 class="card-title"><%= @booking.van.title %></h5>
            <p class="card-text"><%= @booking.van.description %></p>
            <p class="card-text price mb-0 van-price"><%= number_to_currency(@booking.van.price_per_day, unit: '€', precision: 0) %>/jour</p>
            <div class="van-reviews">
              <div class="d-flex justify-content-between">
                <h2>Avis</h2>
                <%= link_to "Ajouter un avis", new_booking_review_path(@booking), class: 'avis-button' %>
              </div>
              <% if @booking.van.reviews.any? %>
                <% @booking.van.reviews.each do |review| %>
                  <div class="review">
                    <div class="review-stars">
                      <% (1..5).each do |i| %>
                        <span class="star <%= 'filled' if review.rating >= i %>">★</span>
                      <% end %>
                    </div>
                    <p><%= review.comment %></p>
                  </div>
                <% end %>
              <% else %>
                <p><em>Aucun avis pour le moment</em></p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>