config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#home'

  resources :bookings, only: [:index, :show] do
    resources :reviews, only: [:new, :create]
    resources :checkings, only: [:new, :create]
    patch 'cancel'
  end

  resources :vans do
    resources :bookings, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :messages, only: [:create]
  get 'dashboard', to: 'pages#dashboard'
  get 'bookings/:id/messages/new', to: 'messages#new', as: :new_message
  get 'bookings/:id/messages', to: 'messages#show', as: :show_messages

  # Route pour les vans, bookings et reservations du current_user
  get 'my_vans', to: 'vans#my_vans', as: :my_vans
  delete 'my_vans/:id', to: 'vans#destroy', as: :delete_my_van
  get 'my_bookings', to: 'bookings#my_bookings', as: :my_bookings
  get 'my_van_reservations', to: 'vans#reservations', as: :my_van_reservations

  # Routes pour accepter et refuser les réservations
  patch 'my_van_reservations/:booking_id/accept', to: 'vans#accept', as: :accept_my_van_reservation
  patch 'my_van_reservations/:booking_id/reject', to: 'vans#reject', as: :reject_my_van_reservation
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <span>Retrouvez-nous sur</span>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag ("logo.png") %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto pe-3">
        <li class="nav-item active">
            <%= link_to "Accueil", "/", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Nos offres", vans_path, class: "nav-link" %>
          </li>
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
           <i class="fa-regular fa-user avatar dropdown-toggle nav-link" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Ajouter un van", new_van_path, class: "dropdown-item" %>
              <%= link_to "Mes Réservations", my_bookings_path, class: "dropdown-item" %>
              <%= link_to "Mes Vans", my_vans_path, class: "dropdown-item" %>
              <%= link_to "Réservations de mes Vans", my_van_reservations_path, class: "dropdown-item" %>
              <%= link_to "Se déconnecter", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <!--li class="nav-item"-->
            <%= link_to new_user_session_path, class: "nav-link"  do %>
              <i class="fa-regular fa-user"></i>
            <% end %>
          <!--/li-->
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyVanLife</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>